---
- name: Merlin Ansible PyATS
  hosts: WAN:LAN
  gather_facts: no
  connection: network_cli
  collections:
    - clay584.genie

  tasks:


############# PARSE SHOW IP INTERFACE BRIEF IOS ##############
  - block:

    - name: show ip interface brief
      ios_command:
        commands:
          - show ip interface brief
      register: ip_int_br_raw
      tags: sip


    - name: Set Fact Genie Filter 
      set_fact:
        pyats_ip_int_br: "{{ ip_int_br_raw['stdout'][0] | parse_genie(command='show ip interface brief', os='ios') }}"
      tags: sip


    - name: Create CSV
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/sh_ip_int_br_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Show_IP_Interface_Brief/{{ inventory_hostname }}.csv
      tags: sip


    - name: Create HTML
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/sh_ip_int_br_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Show_IP_Interface_Brief/{{ inventory_hostname }}.html
      tags: sip

    - name: Create MarkDown File
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/sh_ip_int_br_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Show_IP_Interface_Brief/{{ inventory_hostname }}.md
      tags: sip


############# PARSE SHOW CDP NEIGHBORS IOS ##############
  - block:

    - name: show cdp neighbors
      ios_command:
        commands:
          - show cdp neighbors
      register: cdp_neigbors
      tags: cdp


    - name: Set Fact Genie Filter 
      set_fact:
        set_cdp_neighbor: "{{ cdp_neigbors['stdout'][0] | parse_genie(command='show cdp neighbors', os='ios') }}"
      tags: cdp

    - name: Debug Output 
      debug: 
       var: set_cdp_neighbor
      tags: cdp


    - name: Create CSV
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/sh_cdp_neighbor_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Show_CDP_Neighbors/{{ inventory_hostname }}.csv
      tags: cdp


    - name: Create HTML
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/sh_cdp_neighbor_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Show_CDP_Neighbors/{{ inventory_hostname }}.html
      tags: cdp

    - name: Create MarkDown File
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/sh_cdp_neighbor_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Show_CDP_Neighbors/{{ inventory_hostname }}.md
      tags: cdp

   

############# LEARN PYATS IOS ##############

- name: Merlin Ansible PyATS Learn
  hosts: WAN:LAN
  gather_facts: no
  connection: local
  collections:
    - clay584.genie

  tasks:


  - block:

    - name: Learn PyATS - ARP
      learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "creds"
        password: "creds"
        os: iosxe
        feature: arp
      register: learned_arp
      tags: learn_arp

    - name: Debug PyATS
      debug:
        msg: "{{ learned_arp.genie.arp }}"
      tags: learn_arp


    - name: Create CSV - Learn ARP
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_arp_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ARP/{{ inventory_hostname }}.csv
      tags: learn_arp

    - name: Create HTML - Learn ARP
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_arp_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ARP/{{ inventory_hostname }}.html
      tags: learn_arp

    - name: Create Mark Down - Learn ARP
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_arp_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ARP/{{ inventory_hostname }}.md
      tags: learn_arp


    - name: Learn PyATS - ACL
      learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "creds"
        password: "creds"
        os: iosxe
        feature: acl
      register: learned_acl
      tags: learn_acl

    - name: Debug PyATS
      debug:
        msg: "{{ learned_acl.genie.acl }}"
      tags: learn_acl


    - name: Create CSV - Learn ACL
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_acl_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ACL/{{ inventory_hostname }}.csv
      tags: learn_acl


    - name: Create HTML - Learn ACL
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_acl_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ACL/{{ inventory_hostname }}.html
      tags: learn_acl

    - name: Create Mark Down - Learn ACL
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_acl_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ACL/{{ inventory_hostname }}.md
      tags: learn_acl



    - name: Learn PyATS - VRF
      learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "creds"
        password: "creds"
        os: iosxe
        feature: vrf
      register: learned_vrf
      tags: learn_vrf

    - name: Debug PyATS
      debug:
        msg: "{{ learned_vrf.genie.vrf }}"
      tags: learn_vrf


    - name: Create CSV - Learn VRF
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_vrf_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_VRF/{{ inventory_hostname }}.csv
      tags: learn_vrf


    - name: Create HTML - Learn VRF
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_vrf_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_VRF/{{ inventory_hostname }}.html
      tags: learn_vrf

    - name: Create Mark Down - Learn VRF
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_vrf_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_VRF/{{ inventory_hostname }}.md
      tags: learn_vrf



    - name: Learn PyATS - INTERFACE
      learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "creds"
        password: "creds"
        os: iosxe
        feature: interface
      register: learned_interface
      tags: learn_interface

    - name: Debug PyATS
      debug:
        msg: "{{ learned_interface.genie.interface }}"
      tags: learn_interface


    - name: Create CSV - Learn INTERFACE
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_interface_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_INTERFACE/{{ inventory_hostname }}.csv
      tags: learn_interface


    - name: Create HTML - Learn INTERFACE
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_interface_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_INTERFACE/{{ inventory_hostname }}.html
      tags: learn_interface

    - name: Create Mark Down - Learn INTERFACE
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_interface_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_INTERFACE/{{ inventory_hostname }}.md
      tags: learn_interface



    - name: Learn PyATS - NTP
      learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "creds"
        password: "creds"
        os: iosxe
        feature: ntp
      register: learned_ntp
      tags: learn_ntp

    - name: Debug PyATS
      debug:
        msg: "{{ learned_ntp.genie.ntp.vrf }}"
      tags: learn_ntp


    - name: Create CSV - Learn NTP
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_ntp_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_NTP/{{ inventory_hostname }}.csv
      tags: learn_ntp


    - name: Create HTML - Learn NTP
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_ntp_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_NTP/{{ inventory_hostname }}.html
      tags: learn_ntp

    - name: Create Mark Down - Learn NTP
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_ntp_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_NTP/{{ inventory_hostname }}.md
      tags: learn_ntp




    - name: Learn PyATS - OSPF
      learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "creds"
        password: "creds"
        os: iosxe
        feature: ospf
      register: learned_ospf
      tags: learn_ospf

    - name: Debug PyATS
      debug:
        msg: "{{ learned_ospf.genie.ospf.vrf }}"
      tags: learn_ospf


    - name: Create CSV - Learn OSPF
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_ospf_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_OSPF/{{ inventory_hostname }}.csv
      tags: learn_ospf


    - name: Create HTML - Learn OSPF
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_ospf_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_OSPF/{{ inventory_hostname }}.html
      tags: learn_ospf

    - name: Create Mark Down - Learn OSPF
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_ospf_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_OSPF/{{ inventory_hostname }}.md
      tags: learn_ospf


    - name: Learn PyATS - ROUTING
      learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "creds"
        password: "creds"
        os: iosxe
        feature: routing
      register: learned_routing
      tags: learn_routing

    - name: Debug PyATS
      debug:
        msg: "{{ learned_routing.genie.routing.vrf }}"
      tags: learn_routing


    - name: Create CSV - Learn ROUTING
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_routing_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ROUTING/{{ inventory_hostname }}.csv
      tags: learn_routing


    - name: Create HTML - Learn ROUTING
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_routing_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ROUTING/{{ inventory_hostname }}.html
      tags: learn_routing

    - name: Create Mark Down - Learn ROUTING
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_routing_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_ROUTING/{{ inventory_hostname }}.md
      tags: learn_routing


    - name: Learn PyATS - LLDP INTERFACES
      learn_genie:
        host: "{{ ansible_host }}"
        port: 22
        protocol: ssh
        username: "xa"
        password: "xa"
        os: ios
        feature: lldp
      register: learned_lldp
      tags: learn_lldp

    - name: Debug PyATS
      debug:
        msg: "{{ learned_lldp.genie.lldp.interfaces }}"
      tags: learn_lldp



    - name: Create CSV - Learn LLDP INTERFACES
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_lldp_csv.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_LLDP/{{ inventory_hostname }}.csv
      tags: learn_lldp


    - name: Create HTML - Learn LLDP INTERFACES
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_lldp_html.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_LLDP/{{ inventory_hostname }}.html
      tags: learn_lldp

    - name: Create Mark Down - Learn LLDP INTERFACES
      ansible.builtin.template:
        src: ../templates/ansible/cisco/ios/learned_lldp_md.j2
        dest: ../Camelot/Cisco/Ansible/IOS/Learned_LLDP/{{ inventory_hostname }}.md
      tags: learn_lldp